apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-web
  namespace: kubernetes-cluster-ravindrakumar
  labels:
    app: nagp-web
spec:
  template:
    metadata:
      labels:
        app: nagp-web
        type: web
    spec:
      containers:
      - name: nagp-web
        image: ravindrahbtik11/i-ravindrakumar-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
  replicas: 4
  selector:
    matchLabels:
      app: nagp-web
      type: web
        
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagp-web
  name: nagp-web
  namespace: kubernetes-cluster-ravindrakumar
spec:
  ports:
  - nodePort: 31310
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    app: nagp-web
    type: web
  type: LoadBalancer

      
      
      
      
      
  
