apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-web-main
  namespace: kubernetes-cluster-ravindrakumar
  labels:
    app: nagp-web-main
spec:
  template:
    metadata:
      labels:
        app: nagp-web-main
        type: web-main
    spec:
      containers:
      - name: nagp-web-main
        image: ravindrahbtik11/i-ravindrakumar-web-main:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  replicas: 4
  selector:
    matchLabels:
      app: nagp-web-main
      type: web-main
        
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagp-web-main
  name: nagp-web-main
  namespace: kubernetes-cluster-ravindrakumar
spec:
  ports:
  - nodePort: 31430
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    app: nagp-web-main
    type: web-main
  type: LoadBalancer

      
      
      
      
      
  
