apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-web-main
  namespace: kubernetes-cluster-ravindrakumar
  labels:
    app: nagp-web-main
spec:
  template:
    metadata:
      labels:
        app: nagp-web-main
        type: web-main
    spec:
      containers:
      - name: nagp-web-main
        image: ravindrahbtik11/i-ravindrakumar-web-main:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: nagp-web-main
      type: web-main
      
      
      
      
      
  
