apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-product-dev
  namespace: kubernetes-cluster-ravindrakumar
  labels:
    app: nagp-product-dev
spec:
  template:
    metadata:
      labels:
        app: nagp-product-dev
        type: product
    spec:
      containers:
      - name: nagp-product-dev
        image: ravindrahbtik11/i-ravindrakumar-product-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 443
  replicas: 2
  selector:
    matchLabels:
      app: nagp-product-dev
      type: product
  strategy:
    type: Recreate
        
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagp-product-dev
  name: nagp-product-dev
  namespace: kubernetes-cluster-ravindrakumar
spec:
  ports:
  - nodePort: 31450
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  selector:
    app: nagp-product-dev
    type: product
  type: LoadBalancer