apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nagp-hpa-dev
  namespace: kubernetes-cluster-ravindrakumar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nagp-main-dev
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60