apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagp-web-main
  name: nagp-web-main
  namespace: kubernetes-cluster-ravindrakumar
spec:
  ports:
  - nodePort: 31530
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  selector:
    app: nagp-web-main
    type: web-main
  type: LoadBalancer
