apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagp-product-dev
  name: nagp-product-dev
  namespace: kubernetes-cluster-ravindrakumar
spec:
  ports:
  - nodePort: 31110
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nagp-product-dev
    type: develop
  type: LoadBalancer